name: Build AppImage

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build binary
      run: |
        pyinstaller --onefile --name QRScanner main.py

    - name: Make AppImage folder
      run: |
        mkdir -p AppDir/usr/bin
        cp dist/QRScanner AppDir/usr/bin/
        mkdir -p AppDir/usr/share/applications
        mkdir -p AppDir/usr/share/icons
        # Tạo file .desktop
        cat > AppDir/usr/share/applications/QRScanner.desktop <<EOF
        [Desktop Entry]
        Type=Application
        Name=QRScanner
        Exec=QRScanner
        Icon=QRScanner
        Categories=Utility;
        EOF
        # Tạo icon placeholder
        echo "fake icon" > AppDir/usr/share/icons/QRScanner.png

    - name: Install appimagetool
      run: |
        sudo apt-get update
        sudo apt-get install -y appimagetool

    - name: Build AppImage
      run: |
        appimagetool AppDir QRScanner.AppImage

    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        name: QRScanner-AppImage
        path: QRScanner.AppImage
